---
- hosts: all
  become: yes
  tasks:
  - name: update ubuntu
    apt:
      update_cache: yes
      state: present
    when: ansible_os_family == "debian"    
  - name: install apache packages
    apt:
      name: "apache2"
      state: present
    when: ansible_os_family == "debian"  
    notify:
      - restart   apache
  - name: install httpd
    yum: 
      name: "httpd"
      state: present
    when: ansible_os_family == "rhel"
    notify:
      -restart  httpd  
  - name: install php
    package:
      name: "{{ item }}"
      state: present
    loop:
      - php
      - php-mysql
    notify:
      - restart   apache
      - restart  httpd
  - name: copy infofiles
    copy:
      src: /home/ansible/info/info.php
      dest: /var/www/html/info.php
    notify:
      - restart apache
      - restart httpd 
  handlers:
  - name: restart apache
    service: 
      name: apache2
      state: restarted
    when: ansible_os_family == "debian"  
  - name: restart httpd 
    service:
      name: httpd
      state: restarted
    when: ansible_os_family == "rhel"  


