---
- hosts: all
  become: yes
  tasks:
  - name: update ubuntu
    apt:
      update_cache: yes
      state: present
    when: ansible_os_family == "debian"         
  - name: install apache packages
    package:
      name: "{{ package_name }}"
      state: present
    notify:
      - restart   
  - name: install php
    package:
      name: "{{ item }}"
      state: present
    loop:
      - php
      - php-mysql
    notify:
      - restart   
  - name: copy infofiles
    copy:
      src: info.php
      dest: /var/www/html/info.php
  handlers:
  - name: restart 
    service: 
      name: "{{ package_name }}"
      state: restarted




